server:
    port: 4000

spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 15Mb

logging:
  file: .log/gateway.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000

ribbon:
  ReadTimeout: 90000
  ConnectTimeout: 90000

