server:
    port: 8080

spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 15Mb

zuul:
  prefix: /api
  strip-prefix: true
  routes:
    config-server:
      path: /config-server/**
      serviceId: config-server
    config-server-api:
      path: /config/server/**
      serviceId: config-server
      strip-prefix: false
    core-test:
      path: /core-test/**
    core-test-api:
      path: /core/test/**
      serviceId: core-test
      strip-prefix: false


logging:
  file: .log/gateway.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000

ribbon:
  ReadTimeout: 90000
  ConnectTimeout: 90000

